accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_page, name="logout"),
]

apphome/urls.py
from django.urls import path
from . import views

app_name = 'apphome'

urlpatterns = [
    path('', views.index, name='index'),

]

doctors/urls.py
from django.urls import path, re_path
from .import views

app_name = 'doctors'

urlpatterns = [
    path('', views.doctor_page, name='doctor_page'),
    path('add-patient/', views.addpatient, name="add-patient"),
    path('all-patients/', views.allpatients, name="all-patients"),
    path('<int:patient_id>/', views.patient_detail, name="patient_detail"),

    path('<int:patient_id>/result/', views.prediction_result, name="prediction_result"),
]

predictionsys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  # For using static files
from django.conf.urls.static import static  # For using static files
from django.conf import settings  # For using media files
from apphome import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctors/', include('doctors.urls')),
    path('accounts/', include('accounts.urls')),
    path('apphome/', include('apphome.urls')),
    path('', home_views.index, name="home"),

]

# static files
urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# username = admin
# password = passhnd2

accounts/models.py
from django.db import models

# Create your models here.

apphome/models.py
from django.db import models

# Create your models here.

doctors/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse
from datetime import date, datetime

# Create your models here.


GENDER_CHOICES = (
    ('Male', 'M'),
    ('Female', 'F'),
)


class Patient(models.Model):
    name = models.CharField(max_length=250)
    sex = models.CharField(choices=GENDER_CHOICES, max_length=6, default='Male')
    date_of_birth = models.DateField(blank=False, null=True)
    phone = models.CharField(max_length=11, default='08000000000')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('doctors:patient_detail', args=[self.id])

    @property
    def age(self):
        return int((datetime.now().date() - self.date_of_birth).days / 365.25)


class Symptom(models.Model):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE, primary_key=True)
    age = models.IntegerField()
    chest_pain_type = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(3)])
    blood_pressure = models.IntegerField()
    cholestoral_in_mg = models.IntegerField()
    fasting_blood_sugar = models.BooleanField()
    electrocardiographic_result = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(2)])
    maximum_heart_rate_achieved = models.IntegerField()
    result = models.CharField(max_length=20, default='No Result')

    def __str__(self):
        return self.patient.name


"""
from doctors.models import Patient
>>> p1 = Patient(id=1, name="Akinwole Akin Kayode")
>>> p1.save()
"""

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

doctors/forms.py
from django import forms
from .models import Patient, Symptom


class PatientCreationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Surname and Other Names'}))
    date_of_birth = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'year-month-day'}))

    class Meta:
        model = Patient
        fields = ('name', 'sex', 'date_of_birth', 'phone')


""""
class PatientEditForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    date_of_birth = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    class Meta:
        model = Patient
        fields = ('name', 'date_of_birth',)
"""


class SymptomForm(forms.ModelForm):
    class Meta:
        model = Symptom
        exclude = ('result',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.

def login_page(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('doctors:all-patients')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_page(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')

apphome/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'apphome/index.html')

doctors/views.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PatientCreationForm, SymptomForm
from .models import Patient, Symptom
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import numpy as np
import joblib


# Create your views here.

@login_required
def doctor_page(request):
    return render(request, 'doctors/doctor_page.html')


@login_required
def addpatient(request):
    if request.method == 'POST':
        patient_form = PatientCreationForm(request.POST)
        if patient_form.is_valid():
            patient_form.save()
            messages.success(request, "Patient creation successful.")
            return redirect('doctors:add-patient')
    else:
        patient_form = PatientCreationForm()
    return render(request, 'doctors/addpatient.html', {'patient_form': patient_form})


@login_required
def allpatients(request):
    patient_list = Patient.objects.all().order_by('name')
    # Search code
    query = request.GET.get('q')
    if query:
        patient_list = Patient.objects.filter(
            Q(name__icontains=query) |
            Q(pk__icontains=query)
        )

    # Search code ends
    page = request.GET.get('page', 1)
    paginator = Paginator(patient_list, 10)
    try:
        patients = paginator.page(page)
    except PageNotAnInteger:
        patients = paginator.page(1)
    except EmptyPage:
        patients = paginator.page(paginator.num_pages)
    return render(request, 'doctors/allpatients.html', {'patients': patients})


@login_required
def patient_detail(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    model_path = 'ml_model/model.pkl'
    value = ''

    symptom_form = SymptomForm(request.POST or None)
    if request.method == 'POST':
        if symptom_form.is_valid():
            instance = symptom_form.save(commit=False)

            age = int(request.POST.get('age'))
            trestbps = int(request.POST.get('blood_pressure'))
            chol = int(request.POST.get('cholestoral_in_mg'))
            fbs = bool(request.POST.get('fasting_blood_sugar'))
            restecg = int(request.POST.get('electrocardiographic_result'))
            thalach = int(request.POST.get('maximum_heart_rate_achieved'))
            cp = int(request.POST.get('chest_pain_type'))

            user_data = np.array([[age, trestbps, chol, fbs, restecg, thalach, cp]]).reshape(1, 7)
            svc = joblib.load(open(model_path, 'rb'))
            prediction = svc.predict(user_data)
            if int(prediction[0]) == 1:
                value = 'POSITIVE'
            elif int(prediction[0]) == 0:
                value = 'NEGATIVE'

            instance.result = prediction[0]
            instance.save()
            symptom_form = SymptomForm()
            messages.success(request, "Prediction successful.")

    else:
        symptom_form = SymptomForm()

    context = {
        'patient': patient,
        'symptom_form': symptom_form,
        'val': value,
    }
    return render(request, 'doctors/patientdetail.html', context)


def prediction_result(request, patient_id):
    result = get_object_or_404(Symptom, pk=patient_id)
    return render(request, 'doctors/result.html', {'result': result})

accounts/templates/accounts/login.html
{% load static %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html>
    <head>
        <title>Staff - Login</title>
        <!-- Bootstrap core CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <!-- <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="/static/bootstrap/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

        <link rel="stylesheet" type="text/css" href="/static/style.css">
        <!-- jQuery (necessary for the use of jQuery) -->
        <!-- <script src="/static/bootstrap/js/jquery.min.js"></script> -->
    </head>

    <body>
        <div class="container">
            <form class="login-form-content" action="{% url 'accounts:login' %}" method="post">
                <div class="login-logo">
                    <h5>Log in </h5>
                </div>
                {% csrf_token %}
                {{form|crispy}}
                <!--This is used during redirect after login when you want to access a page that cant be accessed without logging in-->
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <!--end here-->
                <input type="submit" value="Login" class="btn btn-block">
            </form>
        </div>

    <!-- <script src="/static/bootstrap/js/bootstrap.min.js"></script> -->
    </body>
</html>

doctors/templates/doctors/addpatient.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>Doctor's page</title>
        <!-- Bootstrap core CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <!-- <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="/static/bootstrap/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

        <link rel="stylesheet" type="text/css" href="/static/style.css">
        <!-- jQuery (necessary for the use of jQuery) -->
        <!-- <script src="/static/bootstrap/js/jquery.min.js"></script> -->
    </head>

    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                Multi-Cardio Expert System
                {% if user.is_authenticated %}
                    <small style="color: grey">You are logged in as: {{user}} </small>
                {% endif %}
            </a>

          <form class="form-inline ms-auto" action="{% url 'doctors:all-patients' %}">
            <input class="form-control" type="search" placeholder="Patient Search" aria-label="Search" name="q" id="search-input">
            <!-- <button class="btn btn-outline-success" type="submit" id="search-btn"><i class="fa fa-search"></i></button> -->
          </form>
        </nav>


<div id="wrapper">
    <div id="sidebar">
        <h3 style="padding-left: 20px; color: grey;">Dashboard</h3>
        <ul class="sidebar-nav">
            <!--<li><a href="{% url 'doctors:doctor_page' %}">Account</a></li>-->
            <li><a href="{% url 'doctors:add-patient' %}" style="background: #00AEEF;">Add Patient</a></li>
            <li><a href="{% url 'doctors:all-patients' %}">View Patients</a></li>
            <li>
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-block" title="logout" style="text-align:left; padding-left:20px; color:#fff;">Logout</button>
                </form>
            </li>
        </ul>
    </div>

    <!-- page content -->
    <div id="page-content">
        {% include 'alerts.html' %}
        <!--Add a patient -->
        <div class="container">
            <form method="post" id="patient-creation-form">
                <div class="form-head">
                    <h6 style="color:white;">Patient Registration</h6>
			    </div>
                {% csrf_token %}
                {{ patient_form|crispy }}
                <input type="submit" value="Submit" class="btn btn-primary btn-block">
            </form>
        </div>

    </div>

</div>





     <!-- <script src="/static/bootstrap/js/bootstrap.min.js"></script> -->

        <script>
            $(document).ready(function(){
                $(".alert").fadeOut(3000);
            });
        </script>

    </body>
</html>

doctors/templates/doctors/allpatients.html
<!DOCTYPE html>
<html>
    <head>
        <title>Doctor's page</title>
        <!-- Bootstrap core CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <!-- <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="/static/bootstrap/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

        <link rel="stylesheet" type="text/css" href="/static/style.css">
        <!-- jQuery (necessary for the use of jQuery) -->
        <!-- <script src="/static/bootstrap/js/jquery.min.js"></script> -->
    </head>

    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                Multi-Cardio Expert System
                {% if user.is_authenticated %}
                    <small style="color: grey">You are logged in as: {{user}} </small>
                {% endif %}
            </a>

            <form class="form-inline ms-auto" action="{% url 'doctors:all-patients' %}">
                <input class="form-control" type="search" placeholder="Patient Search" aria-label="Search" name="q" id="search-input">
                <!-- <button class="btn btn-outline-success" type="submit" id="search-btn"><i class="fa fa-search"></i></button> -->
            </form>
        </nav>
<div id="wrapper">
    <div id="sidebar">
        <h3 style="padding-left: 20px; color: grey;">Dashboard</h3>
        <ul class="sidebar-nav">
            <!--<li><a href="{% url 'doctors:doctor_page' %}">Account</a></li>-->
            <li><a href="{% url 'doctors:add-patient' %}">Add Patient</a></li>
            <li><a href="{% url 'doctors:all-patients' %}" style="background: #00AEEF;">View Patients</a></li>
            <li>
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-block" title="logout" style="text-align:left; padding-left:20px; color:#fff;">Logout</button>
                </form>
            </li>
        </ul>
    </div>

    <!-- page content -->
    <div id="page-content">

        <!--All patients-->
        <div class="container-fluid">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>PATIENT NAME</th>
                        <th>PHONE NUMBER</th>
                    </tr>
                </thead>
                <tbody>
                {% for patient in patients %}
                    <tr>
                        <td>{{ patient.id }}</td>
                        <td><a href="{{patient.get_absolute_url}}">{{patient.name}}</a></td>
                        <td>{{ patient.phone }}</td>
                    </tr>
                    {% empty %}
                    <div class="container-fluid">
                        <h3>No patient found containing search criteria {{request.GET.q}}</h3>
                    </div>

                {% endfor %}
                </tbody>
            </table>

            <!--pagination-->
            {% if patients.has_other_pages %}
                <ul class="pagination">
                    {% if patients.has_previous %}
                        <li><a class="page-link" href="?page={{patients.previous_page_number}}">&laquo;</a></li>
                    {% else %}
                        <li class="page-link disabled"><span style="color:red;">&laquo;</span></li>
                    {% endif %}

                    {% for i in patients.paginator.page_range %}
                        {% if patients.number == i %}
                            <li class="page-link active"><span style="color:red;"> {{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a class="page-link" href="?page={{ i }}"> {{ i }} </a></li>
                        {% endif %}
                    {% endfor %}

                    {% if patients.has_next %}
                        <li><a class="page-link" href="?page={{ patients.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="page-link disabled"><span style="color:red;">&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}

        </div>

    </div>

</div>

    </body>
</html>

doctors/templates/doctors/diagnose.html
{% extends 'base_template.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid" style="background-color:cornflowerblue; padding-bottom:2px;">
    <h5>WELCOME, This is the Doctor's page</h5>
</div>

<div id="wrapper">
    <div id="sidebar">
        <h3 style="padding-left: 20px; color: grey;">Dashboard</h3>
        <ul class="sidebar-nav">
            <!--<li><a href="{% url 'doctors:doctor_page' %}">Account</a></li>-->
            <li><a href="{% url 'doctors:add-patient' %}">Add Patient</a></li>
            <li><a href="{% url 'doctors:all-patients' %}" style="background: #16A085;">View Patients</a></li>
            <li><a href="{% url 'doctors:heart-prediction' %}" style="background: #16A085;">Patients Results</a></li>
            <li><a href="#">Log out</a></li>
        </ul>
    </div>

    <!-- page content -->
    <div id="page-content">

        <div class="container">
            <form method="post" id="symptom-form">
                {% csrf_token %}
                {{ symptom_form|crispy }}
                <input type="submit" value="Submit" class="btn btn-success btn-block">
            </form>
        </div>

    </div>

</div>
{% endblock %}

doctors/templates/doctors/doctor_page.html
<!DOCTYPE html>
<html>
    <head>
        <title>Doctor's page</title>
        <!-- Bootstrap core CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <!-- <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"> -->
        <!-- <link href="/static/bootstrap/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

        <link rel="stylesheet" type="text/css" href="/static/style.css">
        <!-- jQuery (necessary for the use of jQuery) -->
        <!-- <script src="/static/bootstrap/js/jquery.min.js"></script> -->
    </head>

    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
            <a class="navbar-brand" href="{% url 'home' %}">
                Multi-Cardio Expert System
            </a>

          <form class="form-inline ml-auto" action="{% url 'doctors:all-patients' %}">
                <input class="form-control" type="search" placeholder="Patient Search" aria-label="Search" name="q" id="search-input">
                <button class="btn btn-outline-success" type="submit" id="search-btn"><i class="fa fa-search"></i></button>
          </form>
        </nav>

    <div id="wrapper">
        <div id="sidebar">
            <h3 style="padding-left: 20px; color: grey;">Dashboard</h3>
            <ul class="sidebar-nav">
                <!--<li><a href="{% url 'doctors:doctor_page' %}" style="background: #00AEEF;">Account</a></li>-->
                <li><a href="{% url 'doctors:add-patient' %}">Add Patient</a></li>
                <li><a href="{% url 'doctors:all-patients' %}">View Patients</a></li>
                <li>
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-block" title="logout" style="text-align:left; padding-left:20px; color:#fff;">Logout</button>
                    </form>
                </li>
            </ul>

            <div class="container" style="background-color:black; margin-top:112%;">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <p><small>You are logged in as:</small></p>
                            <p> {{user}} </p>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>

        <!-- page content -->
        <div id="page-content">
            <!--Account-->
            <div class="container-fluid" id="account">
                <h2>This is the Doctor's account page</h2>
            </div>

        </div>

    </div>

    </body>
</html>

doctors/templates/doctors/patientdetail.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>Doctor's page</title>
        <!-- Bootstrap core CSS -->
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="/static/bootstrap/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <link rel="stylesheet" type="text/css" href="/static/style.css">
        <!-- jQuery (necessary for the use of jQuery) -->
        <script src="/static/bootstrap/js/jquery.min.js"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
            <a class="navbar-brand" href="{% url 'home' %}">
                Multi-Cardio Expert System
                {% if user.is_authenticated %}
                    <small style="color: grey">You are logged in as: {{user}} </small>
                {% endif %}
            </a>

          <form class="form-inline ml-auto" action="{% url 'doctors:all-patients' %}">
                <input class="form-control" type="search" placeholder="Patient Search" aria-label="Search" name="q" id="search-input">
                <button class="btn btn-outline-success" type="submit" id="search-btn"><i class="fa fa-search"></i></button>
          </form>
        </nav>

        <div id="wrapper">
            <div id="sidebar">
                <h3 style="padding-left: 20px; color: grey;">Dashboard</h3>
                <ul class="sidebar-nav">
                    <!--<li><a href="{% url 'doctors:doctor_page' %}">Account</a></li>-->
                    <li><a href="{% url 'doctors:add-patient' %}">Add Patient</a></li>
                    <li><a href="{% url 'doctors:all-patients' %}" style="background: #00AEEF;">View Patients</a></li>
                    <li>
                        <form action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-block" title="logout" style="text-align:left; padding-left:20px; color:#fff;">Logout</button>
                        </form>
                    </li>
                </ul>
            </div>

            <!-- page content -->
            <div id="page-content">
                {% include 'alerts.html' %}
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3">
                            <h6>PATIENT ID:  <span style="font-family: courier;">{{ patient.pk }}</span></h6>
                            <h6>PATIENT NAME:  <span style="font-family: courier;">{{ patient.name }}</span></h6>
                            <h6>GENDER:  <span style="font-family: courier;">{{ patient.sex }}</span></h6>
                            <h6>AGE:  <span style="font-family: courier;">{{ patient.age }}</span></h6>
                            <h6>PHONE NO: <span style="font-family: courier;">{{ patient.phone }}</span></h6>
                            <a class="btn btn-dark" href="{% url 'doctors:prediction_result' patient.id %}">Check Result</a>

                        </div>
                        <div class="col-lg-9">
                            <form method="post" id="symptom-form">
                                {% csrf_token %}
                                {{symptom_form.patient|as_crispy_field }}
                                <div class="row">
                                    <div class="col-6">
                                        {{symptom_form.age|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{symptom_form.chest_pain_type|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{symptom_form.blood_pressure|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{symptom_form.cholestoral_in_mg|as_crispy_field }}
                                    </div>
                                </div>

                                {{symptom_form.electrocardiographic_result|as_crispy_field }}
                                {{symptom_form.maximum_heart_rate_achieved|as_crispy_field }}
                                {{symptom_form.fasting_blood_sugar|as_crispy_field }}

                                <input type="submit" value="Submit" class="btn btn-primary btn-block">
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </body>



    <script src="/static/bootstrap/js/bootstrap.min.js"></script>

        <script>
            $(document).ready(function(){
                $(".alert").slideUp("3000");
            });
        </script>


</html>

doctors/templates/doctors/result_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <div class="row">
                <h6>PATIENT ID:  <span style="font-family: courier;">{{ patient.pk }}</span></h6>
                <h6>PATIENT NAME:  <span style="font-family: courier;">{{ patient.name }}</span></h6>
                <h6>GENDER:  <span style="font-family: courier;">{{ patient.sex }}</span></h6>
                <h6>AGE:  <span style="font-family: courier;">{{ patient.age }}</span></h6>
                <h6>PHONE NO: <span style="font-family: courier;">{{ patient.phone }}</span></h6>
                <hr>
                <h2>Result: {{val}}</h2>
        </div>
    </div>
</body>
</html>

templates/alerts.html
    <div class="container messages">
      {% if messages %}
        {% for message in messages %}
          <p class="alert alert-{{message.tags}}">
            {{message}}
          </p>
        {% endfor %}
      {% endif %}
    </div>